---
title: "Jackson Lab"
author: "yincy"
date: "3/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Nomenclature for Mouse Strains  
JAX Mice are named according to the guidelines set by the International Committee on Standardized Genetic Nomenclature for Mice, and strain names are revised as necessary to conform to these guidelines.  

Understanding appropriate nomenclature is essential due to the complexity of strain names for substrains, transgenics, knockouts, etc.   

The Mouse Genome Informatics (MGI) database is a reliable source of official nomenclature for mouse genes, alleles, and strains; it follows the rules of the International Committe on Standized Genetic Nomenclature for Mice.  

## Nomenclature for genetically engineered mice  
Nomenclature for chemically induced and targeted mutations follow the same guidelines as described for mice with spontaneous mutations (see “Nomenclature for Mice with Spontaneous Mutations”). Alleles are designated either by the chemical mutagen or by the abbreviation “tm” (targeted mutation), followed by a number and the laboratory registration code, and selection criteria superscripted to the gene symbol (**e.g., Apoa1^tm1Unc^**).  

## Nomenclature for mice with spontaneous mutations  
Spontaneous mutations occur very rarely and may alter the normal phenotype of a strain.  

##### Applications
<a style='color:blue;text-align:left'>Mice with spontaneous mutations are useful for elucidating basic biological processes, studying relationships between gene mutations and disease phenotypes, and modeling human disease</a>. Research applications are included on strain data sheets in the JAX® Mice Database. The applications are compiled using a number of information sources (please refer to Mouse Information Resources), but they are not all-inclusive: rapidly advancing biomedical research continually uncovers new applications and uses for spontaneous mutants. Investigators are strongly encouraged to research a recommended mouse model to be sure it is appropriate for their research.  

##### Nomenclature  
Gene symbols are italicized. Symbols for recessive genes begin with a lower case letter, and symbols for dominant, semi-dominant and co-dominant genes begin with an upper case letter, followed by lower case letters. The gene and allele symbols for mutant genes are the same until the gene is cloned (see “Nomenclature for cloned mutations,” below). Different alleles of a gene may be represented by a superscript to the gene symbol. Nomenclature for a strain with a spontaneous mutation is as follows: C57BL/6J-A^w–J^. When a mutation is maintained on an inbred strain background by mating homozygotes together, the gene symbol is given once. All offspring are affected mutants (phenotypically manifest the genetic mutation).  


# Resources  
- https://www.jax.org/jax-mice-and-services/customer-support/technical-support/genetics-and-nomenclature
